apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-workspace
  namespace: lan-sd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
