apiVersion: v1
kind: ConfigMap
metadata:
  name: sd-nginx-conf
  namespace: lan-sd
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # nagyobb képfeltöltéshez
      client_max_body_size 200m;

      auth_basic "LAN SD WebUI";
      auth_basic_user_file /etc/nginx/auth/htpasswd;

      location / {
        proxy_pass http://sd-webui:3001;

        # gradio/websocket kompat
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
        proxy_redirect off;
      }
    }
